import type { Transaction } from "./types";

/**
 * Jordan — freshman who’s burning cash mid-semester.
 * Heavy delivery, rideshare, nightlife, BNPL — thin cushion, loan refund mostly gone.
 */
export const jordanTransactions: Transaction[] = [
  {
    id: "j-pay-1",
    date: "2026-08-15",
    merchant: "Campus Rec · payroll",
    category: "income",
    amount: 260,
    source: "Student Checking",
    unforeseen: false,
    note: "Short biweekly — missed two shifts",
  },
  {
    id: "j-pay-2",
    date: "2026-08-01",
    merchant: "Campus Rec · payroll",
    category: "income",
    amount: 280,
    source: "Student Checking",
    unforeseen: false,
  },
  {
    id: "j-family",
    date: "2026-08-05",
    merchant: "Mom · Venmo",
    category: "income",
    amount: 150,
    source: "Venmo",
    unforeseen: false,
    note: "Parents cut the stipend after seeing weekend spends",
  },
  {
    id: "j-shock-phone",
    date: "2026-08-12",
    merchant: "Campus Tech · screen repair",
    category: "shopping",
    amount: -129,
    source: "Student Checking",
    unforeseen: true,
    note: "Cracked phone after a party — not budgeted",
    patternKey: "tech_shock",
  },
  {
    id: "j-shock-ticket",
    date: "2026-08-03",
    merchant: "City Parking Authority",
    category: "auto",
    amount: -65,
    source: "Apple Cash",
    unforeseen: true,
    note: "Parking ticket near the stadium",
    patternKey: "auto_shock",
  },
  {
    id: "j-shock-er",
    date: "2026-07-26",
    merchant: "Urgent Care co-pay",
    category: "health",
    amount: -40,
    source: "Student Checking",
    unforeseen: true,
    note: "Walk-in after intramural sprain",
    patternKey: "health_shock",
  },
  // Delivery burn
  {
    id: "j-dd-1",
    date: "2026-08-22",
    merchant: "DoorDash · late-night burrito",
    category: "food",
    amount: -28,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "delivery",
    note: "Includes $5.99 fee + tip",
  },
  {
    id: "j-dd-2",
    date: "2026-08-21",
    merchant: "Uber Eats · poke",
    category: "food",
    amount: -24,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "delivery",
  },
  {
    id: "j-dd-3",
    date: "2026-08-20",
    merchant: "DoorDash · wings",
    category: "food",
    amount: -31,
    source: "Venmo",
    unforeseen: false,
    patternKey: "delivery",
  },
  {
    id: "j-dd-4",
    date: "2026-08-18",
    merchant: "DoorDash · sushi",
    category: "food",
    amount: -36,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "delivery",
  },
  {
    id: "j-dd-5",
    date: "2026-08-16",
    merchant: "Uber Eats · breakfast sandwich",
    category: "food",
    amount: -18,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "delivery",
  },
  // Rideshare
  {
    id: "j-uber-1",
    date: "2026-08-22",
    merchant: "Uber · downtown",
    category: "transport",
    amount: -19,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "rideshare",
  },
  {
    id: "j-uber-2",
    date: "2026-08-21",
    merchant: "Uber · 1am ride home",
    category: "transport",
    amount: -22,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "rideshare",
  },
  {
    id: "j-uber-3",
    date: "2026-08-17",
    merchant: "Lyft · mall",
    category: "transport",
    amount: -14,
    source: "Venmo",
    unforeseen: false,
    patternKey: "rideshare",
  },
  {
    id: "j-uber-4",
    date: "2026-08-14",
    merchant: "Uber · airport run for friend",
    category: "transport",
    amount: -38,
    source: "Student Checking",
    unforeseen: false,
    patternKey: "rideshare",
    note: "Covered a friend’s ride — never paid back",
  },
  // Nightlife / social
  {
    id: "j-bar-1",
    date: "2026-08-21",
    merchant: "The Copper Tap",
    category: "social",
    amount: -47,
    source: "Venmo",
    unforeseen: false,
    patternKey: "nightlife",
  },
  {
    id: "j-bar-2",
    date: "2026-08-16",
    merchant: "House party · Venmo for keg",
    category: "social",
    amount: -35,
    source: "Venmo",
    unforeseen: false,
    patternKey: "nightlife",
  },
  {
    id: "j-concert",
    date: "2026-08-09",
    merchant: "Ticketmaster · last-minute show",
    category: "social",
    amount: -95,
    source: "Student Checking",
    unforeseen: false,
    patternKey: "nightlife",
    note: "FOMO buy — used loan refund leftovers",
  },
  // Gaming / microtransactions
  {
    id: "j-game-1",
    date: "2026-08-19",
    merchant: "PlayStation Store · battle pass",
    category: "shopping",
    amount: -19.99,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "gaming",
  },
  {
    id: "j-game-2",
    date: "2026-08-11",
    merchant: "Steam · skin pack",
    category: "shopping",
    amount: -24.99,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "gaming",
  },
  // BNPL / shopping
  {
    id: "j-bnpl-1",
    date: "2026-08-08",
    merchant: "Klarna · sneakers installment",
    category: "shopping",
    amount: -42,
    source: "Student Checking",
    unforeseen: false,
    patternKey: "bnpl",
    note: "2 of 4 installments on $168 sneakers",
  },
  {
    id: "j-bnpl-2",
    date: "2026-07-25",
    merchant: "Afterpay · headphones",
    category: "shopping",
    amount: -55,
    source: "Student Checking",
    unforeseen: false,
    patternKey: "bnpl",
  },
  {
    id: "j-sub-1",
    date: "2026-08-01",
    merchant: "Discord Nitro + Xbox Game Pass",
    category: "subscriptions",
    amount: -26.98,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "subscriptions",
  },
  {
    id: "j-coffee-1",
    date: "2026-08-22",
    merchant: "Campus Grounds",
    category: "coffee",
    amount: -6.75,
    source: "Campus Card",
    unforeseen: false,
    patternKey: "coffee",
  },
  {
    id: "j-coffee-2",
    date: "2026-08-21",
    merchant: "Campus Grounds",
    category: "coffee",
    amount: -7.25,
    source: "Campus Card",
    unforeseen: false,
    patternKey: "coffee",
  },
  {
    id: "j-coffee-3",
    date: "2026-08-20",
    merchant: "Starbucks",
    category: "coffee",
    amount: -8.4,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "coffee",
  },
];
