import type { Transaction } from "./types";

/**
 * Maya's mock ledger — realistic student life over ~6 weeks.
 * Unforeseen rows power the risk profile (tire, textbook, etc.).
 */
export const mayaTransactions: Transaction[] = [
  // —— Income ——
  {
    id: "tx-pay-0816",
    date: "2026-08-16",
    merchant: "Campus Dining Services · payroll",
    category: "income",
    amount: 420,
    source: "Student Checking",
    unforeseen: false,
    note: "Biweekly campus job deposit",
  },
  {
    id: "tx-pay-0802",
    date: "2026-08-02",
    merchant: "Campus Dining Services · payroll",
    category: "income",
    amount: 420,
    source: "Student Checking",
    unforeseen: false,
  },
  {
    id: "tx-pay-0719",
    date: "2026-07-19",
    merchant: "Campus Dining Services · payroll",
    category: "income",
    amount: 410,
    source: "Student Checking",
    unforeseen: false,
  },

  // —— Unforeseen shocks (risk evidence) ——
  {
    id: "tx-tire",
    date: "2026-08-09",
    merchant: "Campus Auto Care",
    category: "auto",
    amount: -85,
    source: "Student Checking",
    unforeseen: true,
    note: "Flat tire after night shift — not budgeted",
    patternKey: "auto_shock",
  },
  {
    id: "tx-textbook",
    date: "2026-08-18",
    merchant: "University Bookstore",
    category: "education",
    amount: -62,
    source: "Student Checking",
    unforeseen: true,
    note: "Required stats textbook added mid-syllabus",
    patternKey: "education_shock",
  },
  {
    id: "tx-pharmacy",
    date: "2026-07-28",
    merchant: "Campus Health Pharmacy",
    category: "health",
    amount: -34,
    source: "Apple Cash",
    unforeseen: true,
    note: "Urgent Rx after clinic visit",
    patternKey: "health_shock",
  },
  {
    id: "tx-charger",
    date: "2026-07-22",
    merchant: "Campus Tech Store",
    category: "shopping",
    amount: -45,
    source: "Student Checking",
    unforeseen: true,
    note: "Replacement laptop charger before midterms",
    patternKey: "tech_shock",
  },
  {
    id: "tx-locksmith",
    date: "2026-07-11",
    merchant: "Night Owl Locksmith",
    category: "other",
    amount: -40,
    source: "Venmo",
    unforeseen: true,
    note: "Locked out of apartment after late lab",
    patternKey: "housing_shock",
  },

  // —— Recurring discretionary patterns (tip evidence) ——
  {
    id: "tx-uber-1",
    date: "2026-08-21",
    merchant: "Uber · downtown",
    category: "transport",
    amount: -14,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "uber",
  },
  {
    id: "tx-uber-2",
    date: "2026-08-17",
    merchant: "Uber · campus → apartment",
    category: "transport",
    amount: -11,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "uber",
  },
  {
    id: "tx-uber-3",
    date: "2026-08-12",
    merchant: "Uber · grocery run",
    category: "transport",
    amount: -9,
    source: "Venmo",
    unforeseen: false,
    patternKey: "uber",
  },
  {
    id: "tx-uber-4",
    date: "2026-08-05",
    merchant: "Uber · library late night",
    category: "transport",
    amount: -12,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "uber",
  },
  {
    id: "tx-uber-5",
    date: "2026-07-30",
    merchant: "Uber · airport drop (friend)",
    category: "transport",
    amount: -18,
    source: "Venmo",
    unforeseen: false,
    patternKey: "uber",
  },
  {
    id: "tx-delivery-1",
    date: "2026-08-20",
    merchant: "DoorDash · Thai Bowl",
    category: "food",
    amount: -22,
    source: "Apple Cash",
    unforeseen: false,
    note: "Includes $4.99 delivery fee",
    patternKey: "delivery",
  },
  {
    id: "tx-delivery-2",
    date: "2026-08-14",
    merchant: "Uber Eats · burrito",
    category: "food",
    amount: -19,
    source: "Venmo",
    unforeseen: false,
    patternKey: "delivery",
  },
  {
    id: "tx-delivery-3",
    date: "2026-08-07",
    merchant: "DoorDash · sushi",
    category: "food",
    amount: -27,
    source: "Student Checking",
    unforeseen: false,
    patternKey: "delivery",
  },
  {
    id: "tx-coffee-1",
    date: "2026-08-22",
    merchant: "Campus Grounds",
    category: "coffee",
    amount: -5.5,
    source: "Campus Card",
    unforeseen: false,
    patternKey: "coffee",
  },
  {
    id: "tx-coffee-2",
    date: "2026-08-21",
    merchant: "Campus Grounds",
    category: "coffee",
    amount: -6.25,
    source: "Campus Card",
    unforeseen: false,
    patternKey: "coffee",
  },
  {
    id: "tx-coffee-3",
    date: "2026-08-19",
    merchant: "Campus Grounds",
    category: "coffee",
    amount: -5.5,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "coffee",
  },
  {
    id: "tx-coffee-4",
    date: "2026-08-15",
    merchant: "Starbucks near quad",
    category: "coffee",
    amount: -6.75,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "coffee",
  },
  {
    id: "tx-coffee-5",
    date: "2026-08-11",
    merchant: "Campus Grounds",
    category: "coffee",
    amount: -5.5,
    source: "Campus Card",
    unforeseen: false,
    patternKey: "coffee",
  },
  {
    id: "tx-coffee-6",
    date: "2026-08-08",
    merchant: "Campus Grounds",
    category: "coffee",
    amount: -5.5,
    source: "Campus Card",
    unforeseen: false,
    patternKey: "coffee",
  },
  {
    id: "tx-sub-spotify",
    date: "2026-08-03",
    merchant: "Spotify Student",
    category: "subscriptions",
    amount: -5.99,
    source: "Student Checking",
    unforeseen: false,
    patternKey: "subscriptions",
  },
  {
    id: "tx-sub-icloud",
    date: "2026-08-01",
    merchant: "iCloud+ 50GB",
    category: "subscriptions",
    amount: -0.99,
    source: "Apple Cash",
    unforeseen: false,
    patternKey: "subscriptions",
  },
  {
    id: "tx-sub-canva",
    date: "2026-07-25",
    merchant: "Canva Pro trial → paid",
    category: "subscriptions",
    amount: -14.99,
    source: "Student Checking",
    unforeseen: false,
    note: "Forgot to cancel trial",
    patternKey: "subscriptions",
  },

  // —— Social / normal life ——
  {
    id: "tx-venmo-dinner",
    date: "2026-08-14",
    merchant: "Venmo · group dinner",
    category: "social",
    amount: -18,
    source: "Venmo",
    unforeseen: false,
    patternKey: "social",
  },
  {
    id: "tx-venmo-concert",
    date: "2026-08-11",
    merchant: "Venmo · Jordan (concert)",
    category: "social",
    amount: -32,
    source: "Venmo",
    unforeseen: false,
    patternKey: "social",
  },
  {
    id: "tx-groceries",
    date: "2026-08-13",
    merchant: "Trader Joe's",
    category: "food",
    amount: -41,
    source: "Student Checking",
    unforeseen: false,
  },
  {
    id: "tx-groceries-2",
    date: "2026-08-06",
    merchant: "Aldi",
    category: "food",
    amount: -28,
    source: "Student Checking",
    unforeseen: false,
  },
  {
    id: "tx-laundry",
    date: "2026-08-10",
    merchant: "Laundry card reload",
    category: "other",
    amount: -15,
    source: "Apple Cash",
    unforeseen: false,
  },
  {
    id: "tx-goal-transfer",
    date: "2026-08-16",
    merchant: "Closer · AirPods reserve",
    category: "transfer",
    amount: -40,
    source: "Student Checking",
    unforeseen: false,
    note: "Scheduled goal contribution",
  },
  {
    id: "tx-autosave",
    date: "2026-08-10",
    merchant: "Closer · weekly auto-save",
    category: "transfer",
    amount: -21,
    source: "Student Checking",
    unforeseen: false,
  },
];

export function sumByPattern(
  transactions: Transaction[],
  patternKey: string
): number {
  return Math.abs(
    transactions
      .filter((t) => t.patternKey === patternKey && t.amount < 0)
      .reduce((s, t) => s + t.amount, 0)
  );
}

export function unforeseenTransactions(transactions: Transaction[]): Transaction[] {
  return transactions.filter((t) => t.unforeseen && t.amount < 0);
}
